[package]
name = "quickbooks-xsd"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
xsd-parser-types = { version = "0.2", features = ["quick-xml"] }

[build-dependencies]
xsd-parser = { version = "1.5", features = ["serde"] }

[features]
generate = []

[[example]]
name = "xml"
path = "examples/xml.rs"
